<?php
/*
 * File generated by ModulesGarden packages system
 *
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.3.7';
$moduleRevision = '531890abfda847fc9bcd944a04aa8e24c22525d1';
$moduleWikiUrl = 'http://www.docs.liquidweb.com/';
